### ISSUE TITLE
warning: `#[inline]` is ignored on function prototypes

### ISSUE THREAD

**Issue by Boscop** [taiki-e/easy-ext#21]
I just switched from `extend` to `easy-ext` but I'm getting this warning, because the attr is applied to the method decl:

![image](https://user-images.githubusercontent.com/535593/88124821-47693480-cbce-11ea-9340-37a40824b706.png)

Btw, is it also still applied to the method impl?

**Comment by taiki-e** [comment]
Thanks for the reporting! I didn't know that `unused_attributes` could warn about this (iirc, previously only `clippy::inline_fn_without_body` warned about this).


> Btw, is it also still applied to the method impl?

Yes, currently all attributes apply to both traits and impls (the fix for this issue (#22) changes `#[inline]` to apply only to impls).
Also, `#[doc]` will be changed in the future to apply only to traits. (#20)

**Comment by taiki-e** [comment]
Published 0.2.2 which fixes this issue.
